# Generated by Django 6.0.2 on 2026-03-02 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(blank=True, max_length=10, null=True)),
                ('plan_description', models.TextField(blank=True, null=True)),
                ('plan_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('storage_type', models.CharField(choices=[('personal', 'Personal'), ('shared', 'Shared'), ('backup', 'Backup'), ('medium', 'Medium'), ('database', 'Database'), ('archive', 'Archive')], default='personal', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('full', 'Full'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('quota_gb', models.BigIntegerField(default=10)),
                ('used_gb', models.BigIntegerField(default=0)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('access_key', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Storage',
                'verbose_name_plural': 'Storages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='media/subscriptions/profile_pics')),
                ('background_pic', models.ImageField(blank=True, null=True, upload_to='media/subscriptions/background_pics')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('icd_code', models.CharField(blank=True, max_length=10, null=True)),
                ('pr_number', models.CharField(blank=True, max_length=10, null=True)),
                ('se_number', models.CharField(blank=True, max_length=10, null=True)),
                ('max_storage_gb', models.BigIntegerField(default=50, help_text='Total quota across all storages')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('current_plans', models.ManyToManyField(blank=True, related_name='current_plans', to='subscriptions.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('available_storage', models.ManyToManyField(blank=True, related_name='available_storage', to='subscriptions.storage')),
                ('current_storage', models.ManyToManyField(blank=True, related_name='current_storage', to='subscriptions.storage')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StorageNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('node_id', models.CharField(help_text='Internal node identifier', max_length=100, unique=True)),
                ('node_type', models.CharField(choices=[('HDD', 'Hdd'), ('SSD', 'Ssd'), ('NVME', 'Nvme'), ('Hybrid', 'Hybrid'), ('Object', 'Object'), ('Block', 'Block'), ('Cold', 'Cold')], default='hdd', max_length=20)),
                ('tier', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='hot', max_length=10)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('full', 'Full'), ('degraded', 'Degraded'), ('failed', 'Failed')], default='online', max_length=20)),
                ('datacenter', models.CharField(blank=True, max_length=100, null=True)),
                ('rack', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mount_path', models.CharField(blank=True, help_text='e.g. /mnt/storage/node01', max_length=500, null=True)),
                ('total_capacity_gb', models.BigIntegerField(default=0)),
                ('used_capacity_gb', models.BigIntegerField(default=0)),
                ('reserved_capacity_gb', models.BigIntegerField(default=0, help_text='Reserved for system use')),
                ('read_speed_mbps', models.IntegerField(blank=True, null=True)),
                ('write_speed_mbps', models.IntegerField(blank=True, null=True)),
                ('iops', models.IntegerField(blank=True, null=True)),
                ('is_replica', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('replica_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replicas', to='subscriptions.storagenode')),
            ],
            options={
                'verbose_name': 'Storage Node',
                'verbose_name_plural': 'Storage Nodes',
                'ordering': ['datacenter', 'name'],
            },
        ),
        migrations.AddField(
            model_name='storage',
            name='nodes',
            field=models.ManyToManyField(blank=True, help_text='Physical nodes backing this logical storage', related_name='logical_storages', to='subscriptions.storagenode'),
        ),
    ]
