# Generated by Django 6.0.2 on 2026-03-03 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="available_storage",
            field=models.ManyToManyField(
                blank=True,
                related_name="profiles_available_storage",
                to="subscriptions.storage",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="current_plans",
            field=models.ManyToManyField(
                blank=True,
                related_name="profiles_current_plans",
                to="subscriptions.plan",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="current_storage",
            field=models.ManyToManyField(
                blank=True,
                related_name="profiles_current_storage",
                to="subscriptions.storage",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="storage",
            name="label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
